### ISSUE TITLE
ToDo's

### ISSUE THREAD

**Issue by chrisoco** [frius94/Social_Media#7]
- [x] Add Comments
- [x] Advanced Person Search
- [x] Add Friend
- [x] Add FriendRequest
- [x] Home Add all Posts of Friends /w Comments
- [x] Edit Profile
- [x] Likes
- [x] Confirmation mail after register (not merged to dev, because no mail server available on localhost)
- [x] Styling improvements + Mobile
- [x] Code Doc
- [x] Code cleanup
- [x] Testing
